root: /
admin_dir: admin/
tpl: /user_data/packages/default/
admin_tpl: /user_data/packages/admin/
image_path: /upload/save_image/
root_dir: E:\Kozocom_Project\eccube\AKI_D
root_urlpath: null
template_code: aki
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: E:\Kozocom_Project\eccube\AKI_D/html
image_save_realdir: E:\Kozocom_Project\eccube\AKI_D/html/upload/save_image
image_temp_realdir: E:\Kozocom_Project\eccube\AKI_D/html/upload/temp_image
user_data_realdir: E:\Kozocom_Project\eccube\AKI_D/html/user_data
block_default_realdir: E:\Kozocom_Project\eccube\AKI_D/src/Eccube/Resource/template/default/Block
block_realdir: E:\Kozocom_Project\eccube\AKI_D/app/template/aki/Block
template_default_realdir: E:\Kozocom_Project\eccube\AKI_D/src/Eccube/Resource/template/default
template_default_html_realdir: E:\Kozocom_Project\eccube\AKI_D/html/template/default
template_admin_realdir: E:\Kozocom_Project\eccube\AKI_D/src/Eccube/Resource/template/admin
template_admin_html_realdir: E:\Kozocom_Project\eccube\AKI_D/html/template/admin
template_realdir: E:\Kozocom_Project\eccube\AKI_D/app/template/aki
template_html_realdir: E:\Kozocom_Project\eccube\AKI_D/html/template/aki
template_temp_realdir: E:\Kozocom_Project\eccube\AKI_D/app/cache/eccube/template
csv_temp_realdir: E:\Kozocom_Project\eccube\AKI_D/app/cache/eccube/csv
plugin_realdir: E:\Kozocom_Project\eccube\AKI_D/app/Plugin
plugin_temp_realdir: E:\Kozocom_Project\eccube\AKI_D/app/cache/plugin
plugin_html_realdir: E:\Kozocom_Project\eccube\AKI_D/html/plugin
admin_urlpath: /template/admin
front_urlpath: /template/aki
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
plugin_urlpath: /plugin
